config/routes.rb
Rails.application.routes.draw do
  root 'pokemons#index'
  resources :pokemons
end

# Prefix Verb   URI Pattern                  Controller#Action
#         root GET    /                            pokemons#index
#     pokemons GET    /pokemons(.:format)          pokemons#index
#              POST   /pokemons(.:format)          pokemons#create
#  new_pokemon GET    /pokemons/new(.:format)      pokemons#new
# edit_pokemon GET    /pokemons/:id/edit(.:format) pokemons#edit
#      pokemon GET    /pokemons/:id(.:format)      pokemons#show
#              PATCH  /pokemons/:id(.:format)      pokemons#update
#              PUT    /pokemons/:id(.:format)      pokemons#update
#              DELETE /pokemons/:id(.:format)      pokemons#destroy

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
    validates :name, presence: true
    validates :description, presence: true
    validates :img_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

    def index
      puts "=========="
      puts "in INDEX"
      puts "=========="
      @pokemon = Pokemon.all
    end

    def show
      puts "=========="
      puts "in SHOW"
      puts "=========="


    end

    def new
      puts "=========="
      puts "in NEW"
      puts "=========="
      @pokemon = Pokemon.new
    end

    def edit
      puts "=========="
      puts "in EDIT"
      puts "=========="
    end

    def create
      puts "=========="
      puts "in CREATE"
      puts "=========="

      @pokemon = Pokemon.new(pokemon_params)

      if @pokemon.save
        redirect_to @pokemon
      else
        render :action => :new
      end
    end

    def update
      puts "=========="
      puts "in UPDATE"
      puts "=========="

      if @pokemon.update(pokemon_params)
        redirect_to @pokemon
      else
        render :action => :edit
      end
    end

    def destroy
      puts "=========="
      puts "in DELETE"
      puts "=========="

      @pokemon.destroy
      redirect_to pokemons_url
    end

    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    def pokemon_params
      params.require(:pokemon).permit(:name, :description, :img_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokedexApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>	
</html>

app/views/pokemons/_form.html.erb
<%= form_for @pokemon do |form| %>
 <div class="formName"> Name: <%= form.text_field :name %></br></div>
 <div class="formDes"> Description: <%= form.text_field :description %></br></div>
  <div class="formImg"> Image: <%= form.text_field :img_url %></br>
  <%= form.submit %>
<% end %></div>

app/views/pokemons/edit.html.erb
<h1>Edit your best friend</h1>

<%= render :partial => 'form' %>

app/views/pokemons/index.html.erb
<h1 class="title">CHOOSE YOUR POKEMON!!!</h1>	

<table class="table">
	<% @pokemon.each do |pokemon| %>
	<tr>
		<td><%= link_to pokemon.name, pokemon_path(pokemon.id) %> </td>	
	</tr>
 
	<% end %>
</table>

<p><%= link_to 'New pokemon', new_pokemon_path %></p>

app/views/pokemons/new.html.erb
<h1 class="title">Let's make a new Pokemon</h1>

<%= render :partial => 'form' %>

app/views/pokemons/show.html.erb
<a  class="best" href="/pokemons/"><h1 class="friend">Here is your best friend</h1></a>
<h5 class="showName"><%= @pokemon.name %></h5>
<h5 class="des"><%= @pokemon.description %></h5>
<h5 class="image"><img src=<%=@pokemon.img_url%>> </h5>
<a href="/pokemons/<%= @pokemon.id %>/edit">Edit</a>